[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
nft_smart_contact = "DtepcQcpNbx4gzMRxs5HJqtmwBvj7hw1eqnvuWNQwaVd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/Documents/SolanaPractice/soltokenlaunch/hrNf4ys6X6cKaYh8E3qFo3igbWk7RqG77fWBGn1TNzF.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
